card_map = {
    "AH": False,
    "KH": False,
    "QH": False,
    "JH": False,
    "10H": False,
    "9H": False,
    "8H": False,
    "7H": False,
    "6H": False,
    "5H": False,
    "4H": False,
    "3H": False,
    "2H": False,

    "AD": False,
    "KD": False,
    "QD": False,
    "JD": False,
    "10D": False,
    "9D": False,
    "8D": False,
    "7D": False,
    "6D": False,
    "5D": False,
    "4D": False,
    "3D": False,
    "2D": False,

    "AC": False,
    "KC": False,
    "QC": False,
    "JC": False,
    "10C": False,
    "9C": False,
    "8C": False,
    "7C": False,
    "6C": False,
    "5C": False,
    "4C": False,
    "3C": False,
    "2C": False,

    "AS": False,
    "KS": False,
    "QS": False,
    "JS": False,
    "10S": False,
    "9S": False,
    "8S": False,
    "7S": False,
    "6S": False,
    "5S": False,
    "4S": False,
    "3S": False,
    "2S": False
}